#include "gentest.hpp"
#include "test.hpp"
auto main() -> int {
    test_simple();
    test_single_diverge();

    // tests generated by AI
    test_branching_paths();
    test_disconnected_states();
    test_empty_automaton();
    test_long_sequence();
    test_long_random_sequence();
}
